/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AppUserData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-28T21:40:30.628+08:00[Asia/Shanghai]")
public class AppUserData {
  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_IPA = "ipa";
  @SerializedName(SERIALIZED_NAME_IPA)
  private String ipa;

  public static final String SERIALIZED_NAME_PLIST = "plist";
  @SerializedName(SERIALIZED_NAME_PLIST)
  private String plist;

  public static final String SERIALIZED_NAME_SHORTEN = "shorten";
  @SerializedName(SERIALIZED_NAME_SHORTEN)
  private String shorten;

  public static final String SERIALIZED_NAME_UDID = "udid";
  @SerializedName(SERIALIZED_NAME_UDID)
  private String udid;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;


  public AppUserData host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public AppUserData ipa(String ipa) {
    
    this.ipa = ipa;
    return this;
  }

   /**
   * Get ipa
   * @return ipa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIpa() {
    return ipa;
  }


  public void setIpa(String ipa) {
    this.ipa = ipa;
  }


  public AppUserData plist(String plist) {
    
    this.plist = plist;
    return this;
  }

   /**
   * Get plist
   * @return plist
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlist() {
    return plist;
  }


  public void setPlist(String plist) {
    this.plist = plist;
  }


  public AppUserData shorten(String shorten) {
    
    this.shorten = shorten;
    return this;
  }

   /**
   * Get shorten
   * @return shorten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShorten() {
    return shorten;
  }


  public void setShorten(String shorten) {
    this.shorten = shorten;
  }


  public AppUserData udid(String udid) {
    
    this.udid = udid;
    return this;
  }

   /**
   * Get udid
   * @return udid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdid() {
    return udid;
  }


  public void setUdid(String udid) {
    this.udid = udid;
  }


  public AppUserData uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppUserData appUserData = (AppUserData) o;
    return Objects.equals(this.host, appUserData.host) &&
        Objects.equals(this.ipa, appUserData.ipa) &&
        Objects.equals(this.plist, appUserData.plist) &&
        Objects.equals(this.shorten, appUserData.shorten) &&
        Objects.equals(this.udid, appUserData.udid) &&
        Objects.equals(this.uuid, appUserData.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, ipa, plist, shorten, udid, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppUserData {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    ipa: ").append(toIndentedString(ipa)).append("\n");
    sb.append("    plist: ").append(toIndentedString(plist)).append("\n");
    sb.append("    shorten: ").append(toIndentedString(shorten)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

