/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * BuyMonthRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-01T22:42:19.023+08:00[Asia/Shanghai]")
public class BuyMonthRequest {
  public static final String SERIALIZED_NAME_APP_UUID = "appUuid";
  @SerializedName(SERIALIZED_NAME_APP_UUID)
  private String appUuid;

  /**
   * Gets or Sets deployMode
   */
  @JsonAdapter(DeployModeEnum.Adapter.class)
  public enum DeployModeEnum {
    INTERNAL("internal"),
    
    OPEN("open");

    private String value;

    DeployModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeployModeEnum fromValue(String value) {
      for (DeployModeEnum b : DeployModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeployModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeployModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeployModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeployModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DEPLOY_MODE = "deployMode";
  @SerializedName(SERIALIZED_NAME_DEPLOY_MODE)
  private DeployModeEnum deployMode;

  /**
   * Gets or Sets level
   */
  @JsonAdapter(LevelEnum.Adapter.class)
  public enum LevelEnum {
    DISABLED("Disabled"),
    
    INHERITED("Inherited"),
    
    INTERNAL("Internal"),
    
    PRIVATE("Private"),
    
    PROTECTED("Protected"),
    
    PUBLIC("Public");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LevelEnum fromValue(String value) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LevelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  private LevelEnum level;

  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  private Integer month;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private String productId;

  public static final String SERIALIZED_NAME_SUB_USER_UUID = "subUserUuid";
  @SerializedName(SERIALIZED_NAME_SUB_USER_UUID)
  private String subUserUuid;

  public static final String SERIALIZED_NAME_SYSTEM_UUID = "systemUuid";
  @SerializedName(SERIALIZED_NAME_SYSTEM_UUID)
  private String systemUuid;

  public static final String SERIALIZED_NAME_USER_UUID = "userUuid";
  @SerializedName(SERIALIZED_NAME_USER_UUID)
  private String userUuid;


  public BuyMonthRequest appUuid(String appUuid) {
    
    this.appUuid = appUuid;
    return this;
  }

   /**
   * Get appUuid
   * @return appUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAppUuid() {
    return appUuid;
  }


  public void setAppUuid(String appUuid) {
    this.appUuid = appUuid;
  }


  public BuyMonthRequest deployMode(DeployModeEnum deployMode) {
    
    this.deployMode = deployMode;
    return this;
  }

   /**
   * Get deployMode
   * @return deployMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeployModeEnum getDeployMode() {
    return deployMode;
  }


  public void setDeployMode(DeployModeEnum deployMode) {
    this.deployMode = deployMode;
  }


  public BuyMonthRequest level(LevelEnum level) {
    
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LevelEnum getLevel() {
    return level;
  }


  public void setLevel(LevelEnum level) {
    this.level = level;
  }


  public BuyMonthRequest month(Integer month) {
    
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMonth() {
    return month;
  }


  public void setMonth(Integer month) {
    this.month = month;
  }


  public BuyMonthRequest price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public BuyMonthRequest productId(String productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProductId() {
    return productId;
  }


  public void setProductId(String productId) {
    this.productId = productId;
  }


  public BuyMonthRequest subUserUuid(String subUserUuid) {
    
    this.subUserUuid = subUserUuid;
    return this;
  }

   /**
   * Get subUserUuid
   * @return subUserUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubUserUuid() {
    return subUserUuid;
  }


  public void setSubUserUuid(String subUserUuid) {
    this.subUserUuid = subUserUuid;
  }


  public BuyMonthRequest systemUuid(String systemUuid) {
    
    this.systemUuid = systemUuid;
    return this;
  }

   /**
   * Get systemUuid
   * @return systemUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSystemUuid() {
    return systemUuid;
  }


  public void setSystemUuid(String systemUuid) {
    this.systemUuid = systemUuid;
  }


  public BuyMonthRequest userUuid(String userUuid) {
    
    this.userUuid = userUuid;
    return this;
  }

   /**
   * Get userUuid
   * @return userUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserUuid() {
    return userUuid;
  }


  public void setUserUuid(String userUuid) {
    this.userUuid = userUuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyMonthRequest buyMonthRequest = (BuyMonthRequest) o;
    return Objects.equals(this.appUuid, buyMonthRequest.appUuid) &&
        Objects.equals(this.deployMode, buyMonthRequest.deployMode) &&
        Objects.equals(this.level, buyMonthRequest.level) &&
        Objects.equals(this.month, buyMonthRequest.month) &&
        Objects.equals(this.price, buyMonthRequest.price) &&
        Objects.equals(this.productId, buyMonthRequest.productId) &&
        Objects.equals(this.subUserUuid, buyMonthRequest.subUserUuid) &&
        Objects.equals(this.systemUuid, buyMonthRequest.systemUuid) &&
        Objects.equals(this.userUuid, buyMonthRequest.userUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appUuid, deployMode, level, month, price, productId, subUserUuid, systemUuid, userUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyMonthRequest {\n");
    sb.append("    appUuid: ").append(toIndentedString(appUuid)).append("\n");
    sb.append("    deployMode: ").append(toIndentedString(deployMode)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    subUserUuid: ").append(toIndentedString(subUserUuid)).append("\n");
    sb.append("    systemUuid: ").append(toIndentedString(systemUuid)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

