/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.minclouds.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UdidProduct
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-28T21:40:30.628+08:00[Asia/Shanghai]")
public class UdidProduct {
  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  private Product month;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private Product network;

  public static final String SERIALIZED_NAME_PLUSAPP = "plusapp";
  @SerializedName(SERIALIZED_NAME_PLUSAPP)
  private Product plusapp;

  public static final String SERIALIZED_NAME_TIMES = "times";
  @SerializedName(SERIALIZED_NAME_TIMES)
  private Product times;

  public static final String SERIALIZED_NAME_USER_UUID = "userUuid";
  @SerializedName(SERIALIZED_NAME_USER_UUID)
  private String userUuid;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  private Product year;


  public UdidProduct month(Product month) {
    
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Product getMonth() {
    return month;
  }


  public void setMonth(Product month) {
    this.month = month;
  }


  public UdidProduct network(Product network) {
    
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Product getNetwork() {
    return network;
  }


  public void setNetwork(Product network) {
    this.network = network;
  }


  public UdidProduct plusapp(Product plusapp) {
    
    this.plusapp = plusapp;
    return this;
  }

   /**
   * Get plusapp
   * @return plusapp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Product getPlusapp() {
    return plusapp;
  }


  public void setPlusapp(Product plusapp) {
    this.plusapp = plusapp;
  }


  public UdidProduct times(Product times) {
    
    this.times = times;
    return this;
  }

   /**
   * Get times
   * @return times
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Product getTimes() {
    return times;
  }


  public void setTimes(Product times) {
    this.times = times;
  }


  public UdidProduct userUuid(String userUuid) {
    
    this.userUuid = userUuid;
    return this;
  }

   /**
   * Get userUuid
   * @return userUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserUuid() {
    return userUuid;
  }


  public void setUserUuid(String userUuid) {
    this.userUuid = userUuid;
  }


  public UdidProduct year(Product year) {
    
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Product getYear() {
    return year;
  }


  public void setYear(Product year) {
    this.year = year;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UdidProduct udidProduct = (UdidProduct) o;
    return Objects.equals(this.month, udidProduct.month) &&
        Objects.equals(this.network, udidProduct.network) &&
        Objects.equals(this.plusapp, udidProduct.plusapp) &&
        Objects.equals(this.times, udidProduct.times) &&
        Objects.equals(this.userUuid, udidProduct.userUuid) &&
        Objects.equals(this.year, udidProduct.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(month, network, plusapp, times, userUuid, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UdidProduct {\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    plusapp: ").append(toIndentedString(plusapp)).append("\n");
    sb.append("    times: ").append(toIndentedString(times)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

