/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.api;

import com.minclouds.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthCodeApi
 */
@Ignore
public class AuthCodeApiTest {

    private final AuthCodeApi api = new AuthCodeApi();

    
    /**
     * 创建APP授权码
     *
     * 创建APP授权码
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAuthCodeTest() throws ApiException {
        String appUuid = null;
        String codeType = null;
        Map<String, Object> response = api.createAuthCode(appUuid, codeType);

        // TODO: test validations
    }
    
}
