/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.api;

import com.minclouds.ApiException;
import com.minclouds.model.Endpoint;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EndpointApi
 */
@Ignore
public class EndpointApiTest {

    private final EndpointApi api = new EndpointApi();

    
    /**
     * 获取签名节点入口
     *
     * 获取签名节点入口
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEndpointTest() throws ApiException {
        Map<String, String> param = null;
        List<Endpoint> response = api.getEndpoint(param);

        // TODO: test validations
    }
    
}
