/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.api;

import com.minclouds.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IPhoneApi
 */
@Ignore
public class IPhoneApiTest {

    private final IPhoneApi api = new IPhoneApi();

    
    /**
     * iPhone设备注册
     *
     * iPhone设备注册
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerTest() throws ApiException {
        Map<String, String> param = null;
        api.register(param);

        // TODO: test validations
    }
    
    /**
     * iPhone设备注册
     *
     * iPhone设备注册
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void register1Test() throws ApiException {
        String param = null;
        api.register1(param);

        // TODO: test validations
    }
    
}
