/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.api;

import com.minclouds.ApiException;
import com.minclouds.model.Product;
import com.minclouds.model.UserProduct;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserProductApi
 */
@Ignore
public class UserProductApiTest {

    private final UserProductApi api = new UserProductApi();

    
    /**
     * 获取平台上用户产品的定价
     *
     * 获取平台上用户产品的定价
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProductTest() throws ApiException {
        UserProduct userProduct = null;
        Product response = api.getUserProduct(userProduct);

        // TODO: test validations
    }
    
}
