/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AppDetail
 */
public class AppDetailTest {
    private final AppDetail model = new AppDetail();

    /**
     * Model tests for AppDetail
     */
    @Test
    public void testAppDetail() {
        // TODO: test AppDetail
    }

    /**
     * Test the property 'accelerateEnable'
     */
    @Test
    public void accelerateEnableTest() {
        // TODO: test accelerateEnable
    }

    /**
     * Test the property 'acceleratePreload'
     */
    @Test
    public void acceleratePreloadTest() {
        // TODO: test acceleratePreload
    }

    /**
     * Test the property 'accessLevel'
     */
    @Test
    public void accessLevelTest() {
        // TODO: test accessLevel
    }

    /**
     * Test the property 'apkLinkAddress'
     */
    @Test
    public void apkLinkAddressTest() {
        // TODO: test apkLinkAddress
    }

    /**
     * Test the property 'appAddress'
     */
    @Test
    public void appAddressTest() {
        // TODO: test appAddress
    }

    /**
     * Test the property 'appCodePlus'
     */
    @Test
    public void appCodePlusTest() {
        // TODO: test appCodePlus
    }

    /**
     * Test the property 'appDomain'
     */
    @Test
    public void appDomainTest() {
        // TODO: test appDomain
    }

    /**
     * Test the property 'appImgs'
     */
    @Test
    public void appImgsTest() {
        // TODO: test appImgs
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'appScore'
     */
    @Test
    public void appScoreTest() {
        // TODO: test appScore
    }

    /**
     * Test the property 'appSignal'
     */
    @Test
    public void appSignalTest() {
        // TODO: test appSignal
    }

    /**
     * Test the property 'appSigned'
     */
    @Test
    public void appSignedTest() {
        // TODO: test appSigned
    }

    /**
     * Test the property 'appSize'
     */
    @Test
    public void appSizeTest() {
        // TODO: test appSize
    }

    /**
     * Test the property 'appStar'
     */
    @Test
    public void appStarTest() {
        // TODO: test appStar
    }

    /**
     * Test the property 'appStatus'
     */
    @Test
    public void appStatusTest() {
        // TODO: test appStatus
    }

    /**
     * Test the property 'appSuffix'
     */
    @Test
    public void appSuffixTest() {
        // TODO: test appSuffix
    }

    /**
     * Test the property 'appType'
     */
    @Test
    public void appTypeTest() {
        // TODO: test appType
    }

    /**
     * Test the property 'appTypeStr'
     */
    @Test
    public void appTypeStrTest() {
        // TODO: test appTypeStr
    }

    /**
     * Test the property 'appVersion'
     */
    @Test
    public void appVersionTest() {
        // TODO: test appVersion
    }

    /**
     * Test the property 'authCodePlus'
     */
    @Test
    public void authCodePlusTest() {
        // TODO: test authCodePlus
    }

    /**
     * Test the property 'autoMobileConfig'
     */
    @Test
    public void autoMobileConfigTest() {
        // TODO: test autoMobileConfig
    }

    /**
     * Test the property 'autoRenew'
     */
    @Test
    public void autoRenewTest() {
        // TODO: test autoRenew
    }

    /**
     * Test the property 'autoSelect'
     */
    @Test
    public void autoSelectTest() {
        // TODO: test autoSelect
    }

    /**
     * Test the property 'banner'
     */
    @Test
    public void bannerTest() {
        // TODO: test banner
    }

    /**
     * Test the property 'bindDomain'
     */
    @Test
    public void bindDomainTest() {
        // TODO: test bindDomain
    }

    /**
     * Test the property 'bundleId'
     */
    @Test
    public void bundleIdTest() {
        // TODO: test bundleId
    }

    /**
     * Test the property 'callback'
     */
    @Test
    public void callbackTest() {
        // TODO: test callback
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'deadline'
     */
    @Test
    public void deadlineTest() {
        // TODO: test deadline
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'developer'
     */
    @Test
    public void developerTest() {
        // TODO: test developer
    }

    /**
     * Test the property 'dynamicMobileConfig'
     */
    @Test
    public void dynamicMobileConfigTest() {
        // TODO: test dynamicMobileConfig
    }

    /**
     * Test the property 'enterpriseSigned'
     */
    @Test
    public void enterpriseSignedTest() {
        // TODO: test enterpriseSigned
    }

    /**
     * Test the property 'fileSize'
     */
    @Test
    public void fileSizeTest() {
        // TODO: test fileSize
    }

    /**
     * Test the property 'fileVersion'
     */
    @Test
    public void fileVersionTest() {
        // TODO: test fileVersion
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'inject'
     */
    @Test
    public void injectTest() {
        // TODO: test inject
    }

    /**
     * Test the property 'installJump'
     */
    @Test
    public void installJumpTest() {
        // TODO: test installJump
    }

    /**
     * Test the property 'installTime'
     */
    @Test
    public void installTimeTest() {
        // TODO: test installTime
    }

    /**
     * Test the property 'installType'
     */
    @Test
    public void installTypeTest() {
        // TODO: test installType
    }

    /**
     * Test the property 'jumpUrl'
     */
    @Test
    public void jumpUrlTest() {
        // TODO: test jumpUrl
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'lastSignTimer'
     */
    @Test
    public void lastSignTimerTest() {
        // TODO: test lastSignTimer
    }

    /**
     * Test the property 'lastVisitTime'
     */
    @Test
    public void lastVisitTimeTest() {
        // TODO: test lastVisitTime
    }

    /**
     * Test the property 'limitType'
     */
    @Test
    public void limitTypeTest() {
        // TODO: test limitType
    }

    /**
     * Test the property 'linkedUuid'
     */
    @Test
    public void linkedUuidTest() {
        // TODO: test linkedUuid
    }

    /**
     * Test the property 'md5'
     */
    @Test
    public void md5Test() {
        // TODO: test md5
    }

    /**
     * Test the property 'mobileConfig'
     */
    @Test
    public void mobileConfigTest() {
        // TODO: test mobileConfig
    }

    /**
     * Test the property 'newAppName'
     */
    @Test
    public void newAppNameTest() {
        // TODO: test newAppName
    }

    /**
     * Test the property 'newBundleId'
     */
    @Test
    public void newBundleIdTest() {
        // TODO: test newBundleId
    }

    /**
     * Test the property 'notification'
     */
    @Test
    public void notificationTest() {
        // TODO: test notification
    }

    /**
     * Test the property 'packAppUuid'
     */
    @Test
    public void packAppUuidTest() {
        // TODO: test packAppUuid
    }

    /**
     * Test the property 'packUdid'
     */
    @Test
    public void packUdidTest() {
        // TODO: test packUdid
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'priceLimit'
     */
    @Test
    public void priceLimitTest() {
        // TODO: test priceLimit
    }

    /**
     * Test the property 'progressType'
     */
    @Test
    public void progressTypeTest() {
        // TODO: test progressType
    }

    /**
     * Test the property 'qrcodeUrl'
     */
    @Test
    public void qrcodeUrlTest() {
        // TODO: test qrcodeUrl
    }

    /**
     * Test the property 'separateType'
     */
    @Test
    public void separateTypeTest() {
        // TODO: test separateType
    }

    /**
     * Test the property 'shortCode'
     */
    @Test
    public void shortCodeTest() {
        // TODO: test shortCode
    }

    /**
     * Test the property 'shortUrl'
     */
    @Test
    public void shortUrlTest() {
        // TODO: test shortUrl
    }

    /**
     * Test the property 'shorten'
     */
    @Test
    public void shortenTest() {
        // TODO: test shorten
    }

    /**
     * Test the property 'showNote'
     */
    @Test
    public void showNoteTest() {
        // TODO: test showNote
    }

    /**
     * Test the property 'signCertUuid'
     */
    @Test
    public void signCertUuidTest() {
        // TODO: test signCertUuid
    }

    /**
     * Test the property 'signHost'
     */
    @Test
    public void signHostTest() {
        // TODO: test signHost
    }

    /**
     * Test the property 'signTime'
     */
    @Test
    public void signTimeTest() {
        // TODO: test signTime
    }

    /**
     * Test the property 'signType'
     */
    @Test
    public void signTypeTest() {
        // TODO: test signType
    }

    /**
     * Test the property 'signedIpa'
     */
    @Test
    public void signedIpaTest() {
        // TODO: test signedIpa
    }

    /**
     * Test the property 'signedMd5'
     */
    @Test
    public void signedMd5Test() {
        // TODO: test signedMd5
    }

    /**
     * Test the property 'signedSize'
     */
    @Test
    public void signedSizeTest() {
        // TODO: test signedSize
    }

    /**
     * Test the property 'unzipCharset'
     */
    @Test
    public void unzipCharsetTest() {
        // TODO: test unzipCharset
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'userAge'
     */
    @Test
    public void userAgeTest() {
        // TODO: test userAge
    }

    /**
     * Test the property 'userCount'
     */
    @Test
    public void userCountTest() {
        // TODO: test userCount
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'videoBackground'
     */
    @Test
    public void videoBackgroundTest() {
        // TODO: test videoBackground
    }

    /**
     * Test the property 'videoMedia'
     */
    @Test
    public void videoMediaTest() {
        // TODO: test videoMedia
    }

}
