/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AppInfo
 */
public class AppInfoTest {
    private final AppInfo model = new AppInfo();

    /**
     * Model tests for AppInfo
     */
    @Test
    public void testAppInfo() {
        // TODO: test AppInfo
    }

    /**
     * Test the property 'appCodePlus'
     */
    @Test
    public void appCodePlusTest() {
        // TODO: test appCodePlus
    }

    /**
     * Test the property 'appImgs'
     */
    @Test
    public void appImgsTest() {
        // TODO: test appImgs
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'appScore'
     */
    @Test
    public void appScoreTest() {
        // TODO: test appScore
    }

    /**
     * Test the property 'appSignal'
     */
    @Test
    public void appSignalTest() {
        // TODO: test appSignal
    }

    /**
     * Test the property 'appSize'
     */
    @Test
    public void appSizeTest() {
        // TODO: test appSize
    }

    /**
     * Test the property 'appStar'
     */
    @Test
    public void appStarTest() {
        // TODO: test appStar
    }

    /**
     * Test the property 'appTypeStr'
     */
    @Test
    public void appTypeStrTest() {
        // TODO: test appTypeStr
    }

    /**
     * Test the property 'appVersion'
     */
    @Test
    public void appVersionTest() {
        // TODO: test appVersion
    }

    /**
     * Test the property 'authCodePlus'
     */
    @Test
    public void authCodePlusTest() {
        // TODO: test authCodePlus
    }

    /**
     * Test the property 'banner'
     */
    @Test
    public void bannerTest() {
        // TODO: test banner
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'developer'
     */
    @Test
    public void developerTest() {
        // TODO: test developer
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'installType'
     */
    @Test
    public void installTypeTest() {
        // TODO: test installType
    }

    /**
     * Test the property 'jumpUrl'
     */
    @Test
    public void jumpUrlTest() {
        // TODO: test jumpUrl
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'lastVisitTime'
     */
    @Test
    public void lastVisitTimeTest() {
        // TODO: test lastVisitTime
    }

    /**
     * Test the property 'newAppName'
     */
    @Test
    public void newAppNameTest() {
        // TODO: test newAppName
    }

    /**
     * Test the property 'qrcodeUrl'
     */
    @Test
    public void qrcodeUrlTest() {
        // TODO: test qrcodeUrl
    }

    /**
     * Test the property 'separateType'
     */
    @Test
    public void separateTypeTest() {
        // TODO: test separateType
    }

    /**
     * Test the property 'shortUrl'
     */
    @Test
    public void shortUrlTest() {
        // TODO: test shortUrl
    }

    /**
     * Test the property 'signType'
     */
    @Test
    public void signTypeTest() {
        // TODO: test signType
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'userAge'
     */
    @Test
    public void userAgeTest() {
        // TODO: test userAge
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'videoBackground'
     */
    @Test
    public void videoBackgroundTest() {
        // TODO: test videoBackground
    }

    /**
     * Test the property 'videoMedia'
     */
    @Test
    public void videoMediaTest() {
        // TODO: test videoMedia
    }

}
