/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BuyMonthRequest
 */
public class BuyMonthRequestTest {
    private final BuyMonthRequest model = new BuyMonthRequest();

    /**
     * Model tests for BuyMonthRequest
     */
    @Test
    public void testBuyMonthRequest() {
        // TODO: test BuyMonthRequest
    }

    /**
     * Test the property 'appUuid'
     */
    @Test
    public void appUuidTest() {
        // TODO: test appUuid
    }

    /**
     * Test the property 'deployMode'
     */
    @Test
    public void deployModeTest() {
        // TODO: test deployMode
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'subUserUuid'
     */
    @Test
    public void subUserUuidTest() {
        // TODO: test subUserUuid
    }

    /**
     * Test the property 'systemUuid'
     */
    @Test
    public void systemUuidTest() {
        // TODO: test systemUuid
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

}
