/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BuyMonthResponse
 */
public class BuyMonthResponseTest {
    private final BuyMonthResponse model = new BuyMonthResponse();

    /**
     * Model tests for BuyMonthResponse
     */
    @Test
    public void testBuyMonthResponse() {
        // TODO: test BuyMonthResponse
    }

    /**
     * Test the property 'appUuid'
     */
    @Test
    public void appUuidTest() {
        // TODO: test appUuid
    }

    /**
     * Test the property 'certUuid'
     */
    @Test
    public void certUuidTest() {
        // TODO: test certUuid
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'deadline'
     */
    @Test
    public void deadlineTest() {
        // TODO: test deadline
    }

    /**
     * Test the property 'flowNum'
     */
    @Test
    public void flowNumTest() {
        // TODO: test flowNum
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'specifics'
     */
    @Test
    public void specificsTest() {
        // TODO: test specifics
    }

    /**
     * Test the property 'subUserUuid'
     */
    @Test
    public void subUserUuidTest() {
        // TODO: test subUserUuid
    }

    /**
     * Test the property 'systemUuid'
     */
    @Test
    public void systemUuidTest() {
        // TODO: test systemUuid
    }

    /**
     * Test the property 'tradeNum'
     */
    @Test
    public void tradeNumTest() {
        // TODO: test tradeNum
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

    /**
     * Test the property 'validKey'
     */
    @Test
    public void validKeyTest() {
        // TODO: test validKey
    }

}
