/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CodeRequest
 */
public class CodeRequestTest {
    private final CodeRequest model = new CodeRequest();

    /**
     * Model tests for CodeRequest
     */
    @Test
    public void testCodeRequest() {
        // TODO: test CodeRequest
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'paid'
     */
    @Test
    public void paidTest() {
        // TODO: test paid
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'subUuid'
     */
    @Test
    public void subUuidTest() {
        // TODO: test subUuid
    }

    /**
     * Test the property 'systemUuid'
     */
    @Test
    public void systemUuidTest() {
        // TODO: test systemUuid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

}
