/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceRegistryRequest
 */
public class DeviceRegistryRequestTest {
    private final DeviceRegistryRequest model = new DeviceRegistryRequest();

    /**
     * Model tests for DeviceRegistryRequest
     */
    @Test
    public void testDeviceRegistryRequest() {
        // TODO: test DeviceRegistryRequest
    }

    /**
     * Test the property 'accessKey'
     */
    @Test
    public void accessKeyTest() {
        // TODO: test accessKey
    }

    /**
     * Test the property 'accessLevel'
     */
    @Test
    public void accessLevelTest() {
        // TODO: test accessLevel
    }

    /**
     * Test the property 'accountUuid'
     */
    @Test
    public void accountUuidTest() {
        // TODO: test accountUuid
    }

    /**
     * Test the property 'appUuid'
     */
    @Test
    public void appUuidTest() {
        // TODO: test appUuid
    }

    /**
     * Test the property 'autoSelect'
     */
    @Test
    public void autoSelectTest() {
        // TODO: test autoSelect
    }

    /**
     * Test the property 'callback'
     */
    @Test
    public void callbackTest() {
        // TODO: test callback
    }

    /**
     * Test the property 'deviceName'
     */
    @Test
    public void deviceNameTest() {
        // TODO: test deviceName
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'imei'
     */
    @Test
    public void imeiTest() {
        // TODO: test imei
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'priceLimit'
     */
    @Test
    public void priceLimitTest() {
        // TODO: test priceLimit
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'serial'
     */
    @Test
    public void serialTest() {
        // TODO: test serial
    }

    /**
     * Test the property 'signType'
     */
    @Test
    public void signTypeTest() {
        // TODO: test signType
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'systemUuid'
     */
    @Test
    public void systemUuidTest() {
        // TODO: test systemUuid
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'udid'
     */
    @Test
    public void udidTest() {
        // TODO: test udid
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
