/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceRegistryResponse
 */
public class DeviceRegistryResponseTest {
    private final DeviceRegistryResponse model = new DeviceRegistryResponse();

    /**
     * Model tests for DeviceRegistryResponse
     */
    @Test
    public void testDeviceRegistryResponse() {
        // TODO: test DeviceRegistryResponse
    }

    /**
     * Test the property 'accountUuid'
     */
    @Test
    public void accountUuidTest() {
        // TODO: test accountUuid
    }

    /**
     * Test the property 'appData'
     */
    @Test
    public void appDataTest() {
        // TODO: test appData
    }

    /**
     * Test the property 'appUuid'
     */
    @Test
    public void appUuidTest() {
        // TODO: test appUuid
    }

    /**
     * Test the property 'bundleId'
     */
    @Test
    public void bundleIdTest() {
        // TODO: test bundleId
    }

    /**
     * Test the property 'callback'
     */
    @Test
    public void callbackTest() {
        // TODO: test callback
    }

    /**
     * Test the property 'certificate'
     */
    @Test
    public void certificateTest() {
        // TODO: test certificate
    }

    /**
     * Test the property 'certificateId'
     */
    @Test
    public void certificateIdTest() {
        // TODO: test certificateId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'flowNum'
     */
    @Test
    public void flowNumTest() {
        // TODO: test flowNum
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'separate'
     */
    @Test
    public void separateTest() {
        // TODO: test separate
    }

    /**
     * Test the property 'signType'
     */
    @Test
    public void signTypeTest() {
        // TODO: test signType
    }

    /**
     * Test the property 'systemUuid'
     */
    @Test
    public void systemUuidTest() {
        // TODO: test systemUuid
    }

    /**
     * Test the property 'tradeNum'
     */
    @Test
    public void tradeNumTest() {
        // TODO: test tradeNum
    }

    /**
     * Test the property 'udid'
     */
    @Test
    public void udidTest() {
        // TODO: test udid
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
