/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Product
 */
public class ProductTest {
    private final Product model = new Product();

    /**
     * Model tests for Product
     */
    @Test
    public void testProduct() {
        // TODO: test Product
    }

    /**
     * Test the property 'append'
     */
    @Test
    public void appendTest() {
        // TODO: test append
    }

    /**
     * Test the property 'commissionType'
     */
    @Test
    public void commissionTypeTest() {
        // TODO: test commissionType
    }

    /**
     * Test the property 'commissionValue'
     */
    @Test
    public void commissionValueTest() {
        // TODO: test commissionValue
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'dynamic'
     */
    @Test
    public void dynamicTest() {
        // TODO: test dynamic
    }

    /**
     * Test the property 'floating'
     */
    @Test
    public void floatingTest() {
        // TODO: test floating
    }

    /**
     * Test the property 'guide'
     */
    @Test
    public void guideTest() {
        // TODO: test guide
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ownerType'
     */
    @Test
    public void ownerTypeTest() {
        // TODO: test ownerType
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'plus'
     */
    @Test
    public void plusTest() {
        // TODO: test plus
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productStatus'
     */
    @Test
    public void productStatusTest() {
        // TODO: test productStatus
    }

    /**
     * Test the property 'realPrice'
     */
    @Test
    public void realPriceTest() {
        // TODO: test realPrice
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
