/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.minclouds.model.PluginEntry;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TestSystem
 */
public class TestSystemTest {
    private final TestSystem model = new TestSystem();

    /**
     * Model tests for TestSystem
     */
    @Test
    public void testTestSystem() {
        // TODO: test TestSystem
    }

    /**
     * Test the property 'accessLevel'
     */
    @Test
    public void accessLevelTest() {
        // TODO: test accessLevel
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'authCount'
     */
    @Test
    public void authCountTest() {
        // TODO: test authCount
    }

    /**
     * Test the property 'callback'
     */
    @Test
    public void callbackTest() {
        // TODO: test callback
    }

    /**
     * Test the property 'codeLimit'
     */
    @Test
    public void codeLimitTest() {
        // TODO: test codeLimit
    }

    /**
     * Test the property 'commission'
     */
    @Test
    public void commissionTest() {
        // TODO: test commission
    }

    /**
     * Test the property 'consume'
     */
    @Test
    public void consumeTest() {
        // TODO: test consume
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'crt'
     */
    @Test
    public void crtTest() {
        // TODO: test crt
    }

    /**
     * Test the property 'defaultZone'
     */
    @Test
    public void defaultZoneTest() {
        // TODO: test defaultZone
    }

    /**
     * Test the property 'deploy'
     */
    @Test
    public void deployTest() {
        // TODO: test deploy
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'enable'
     */
    @Test
    public void enableTest() {
        // TODO: test enable
    }

    /**
     * Test the property 'expend'
     */
    @Test
    public void expendTest() {
        // TODO: test expend
    }

    /**
     * Test the property 'flowSize'
     */
    @Test
    public void flowSizeTest() {
        // TODO: test flowSize
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'linkLimit'
     */
    @Test
    public void linkLimitTest() {
        // TODO: test linkLimit
    }

    /**
     * Test the property 'monthYear'
     */
    @Test
    public void monthYearTest() {
        // TODO: test monthYear
    }

    /**
     * Test the property 'payMode'
     */
    @Test
    public void payModeTest() {
        // TODO: test payMode
    }

    /**
     * Test the property 'payerCount'
     */
    @Test
    public void payerCountTest() {
        // TODO: test payerCount
    }

    /**
     * Test the property 'pem'
     */
    @Test
    public void pemTest() {
        // TODO: test pem
    }

    /**
     * Test the property 'plugins'
     */
    @Test
    public void pluginsTest() {
        // TODO: test plugins
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'publicIp'
     */
    @Test
    public void publicIpTest() {
        // TODO: test publicIp
    }

    /**
     * Test the property 'quota'
     */
    @Test
    public void quotaTest() {
        // TODO: test quota
    }

    /**
     * Test the property 'regionId'
     */
    @Test
    public void regionIdTest() {
        // TODO: test regionId
    }

    /**
     * Test the property 'regionName'
     */
    @Test
    public void regionNameTest() {
        // TODO: test regionName
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'releaseTime'
     */
    @Test
    public void releaseTimeTest() {
        // TODO: test releaseTime
    }

    /**
     * Test the property 'signLimit'
     */
    @Test
    public void signLimitTest() {
        // TODO: test signLimit
    }

    /**
     * Test the property 'signedCount'
     */
    @Test
    public void signedCountTest() {
        // TODO: test signedCount
    }

    /**
     * Test the property 'stack'
     */
    @Test
    public void stackTest() {
        // TODO: test stack
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'systemStatus'
     */
    @Test
    public void systemStatusTest() {
        // TODO: test systemStatus
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'udidLimit'
     */
    @Test
    public void udidLimitTest() {
        // TODO: test udidLimit
    }

    /**
     * Test the property 'useMode'
     */
    @Test
    public void useModeTest() {
        // TODO: test useMode
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'zoneId'
     */
    @Test
    public void zoneIdTest() {
        // TODO: test zoneId
    }

    /**
     * Test the property 'zoneName'
     */
    @Test
    public void zoneNameTest() {
        // TODO: test zoneName
    }

}
