/*
 * 云小朵开发者服务平台
 * 云小朵开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minclouds@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.minclouds.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UdidPayData
 */
public class UdidPayDataTest {
    private final UdidPayData model = new UdidPayData();

    /**
     * Model tests for UdidPayData
     */
    @Test
    public void testUdidPayData() {
        // TODO: test UdidPayData
    }

    /**
     * Test the property 'appCount'
     */
    @Test
    public void appCountTest() {
        // TODO: test appCount
    }

    /**
     * Test the property 'buyData'
     */
    @Test
    public void buyDataTest() {
        // TODO: test buyData
    }

    /**
     * Test the property 'giveData'
     */
    @Test
    public void giveDataTest() {
        // TODO: test giveData
    }

    /**
     * Test the property 'lastPay'
     */
    @Test
    public void lastPayTest() {
        // TODO: test lastPay
    }

    /**
     * Test the property 'limitType'
     */
    @Test
    public void limitTypeTest() {
        // TODO: test limitType
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'payTime'
     */
    @Test
    public void payTimeTest() {
        // TODO: test payTime
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'subUuid'
     */
    @Test
    public void subUuidTest() {
        // TODO: test subUuid
    }

    /**
     * Test the property 'udid'
     */
    @Test
    public void udidTest() {
        // TODO: test udid
    }

    /**
     * Test the property 'userUuid'
     */
    @Test
    public void userUuidTest() {
        // TODO: test userUuid
    }

}
